blank_issues_enabled: true
contact_links:
  - name: Upptime Docs
    url: https://upptime.js.org
    about: Looking for the docs? Go there.
  - name: Filing a issue for the community projects organization in general?
    url: https://github.com/hackclub-community/meta
    about: |
      Please direct meta questions relating to this GitHub organization there (or ask in the #community Slack channel).
